### ISSUE TITLE
create_database_user call results in JSON parse error

### ISSUE THREAD

**Issue by flightjumpr** [influxdata/influxdb-ruby#127]
The following example is given in the documentation

```ruby
database = 'site_development'
new_username = 'foo'
new_password = 'bar'
permission = :write

###with all permissions
influxdb.create_database_user(database, new_username, new_password)
```

This amounts to the following for me

```
JSON::ParserError: A JSON text must at least contain two octets!
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/json-1.8.3/lib/json/common.rb:155:in `new'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/influxdb-0.2.3/lib/influxdb/client/http.rb:88:in `handle_successful_response'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/influxdb-0.2.3/lib/influxdb/client/http.rb:14:in `block in get'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/influxdb-0.2.3/lib/influxdb/client/http.rb:52:in `call'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/influxdb-0.2.3/lib/influxdb/client/http.rb:52:in `connect_with_retry'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/influxdb-0.2.3/lib/influxdb/client/http.rb:11:in `get'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/influxdb-0.2.3/lib/influxdb/query/core.rb:94:in `execute'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/influxdb-0.2.3/lib/influxdb/query/user.rb:8:in `create_database_user'
	from (irb):13
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/martin/.rvm/gems/ruby-2.2.3@cpass/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/martin/Documents/Development/Rails/cpass/bin/rails:9:in `require'
	from /Users/martin/Documents/Development/Rails/cpass/bin/rails:9:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

The execute block in create_database_user seems to be returning an "" source which the parse method is trying to execute upon.

**Comment by dmke** [comment]
Which version of InfluxDB were you using?
