### ISSUE TITLE
when the influxdb server is failing to write getting wrong argument error

### ISSUE THREAD

**Issue by zacksiri** [influxdata/influxdb-ruby#133]
```ruby
ArgumentError: wrong number of arguments (given 2, expected 1)
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/influxer-0.3.1/lib/influxer/rails/client.rb:15:in `log'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/influxdb-0.2.3/lib/influxdb/client/http.rb:57:in `rescue in connect_with_retry'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/influxdb-0.2.3/lib/influxdb/client/http.rb:66:in `connect_with_retry'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/influxdb-0.2.3/lib/influxdb/client/http.rb:25:in `post'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/influxdb-0.2.3/lib/influxdb/query/core.rb:56:in `write'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/influxdb-0.2.3/lib/influxdb/query/core.rb:42:in `write_points'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/influxdb-0.2.3/lib/influxdb/query/core.rb:48:in `write_point'
	from /usr/src/app/app/models/activity/point.rb:10:in `plot'
	from /usr/src/app/app/models/activity.rb:32:in `plot'
	from (irb):7:in `block in irb_binding'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/delegation.rb:46:in `each'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/delegation.rb:46:in `each'
	from (irb):6
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/src/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/r
```

**Comment by dmke** [comment]
Can you update both `influxer` and `influxdb` gems to their most recent versions and try again? I seems like you use `influxer` v0.3.1 while v0.5.1 is the most recent.
