### ISSUE TITLE
"/" character in query gives error

### ISSUE THREAD

**Issue by BernH4** [influxdata/influxdb-ruby#258]
I tried running a query with this simple code:

```rb
require "influxdb"


database = 'homedb'
influxdb = InfluxDB::Client.new  database,
  host: "192.168.178.143",
  port: "8086"

influxdb.query('select * from heizung/pufferspeicher/temp')
```
which gives me error:
```
Traceback (most recent call last):
        5: from query.rb:9:in `<main>'
        4: from /home/bs/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/influxdb-0.8.1/lib/influxdb/query/core.rb:30:in `query'
        3: from /home/bs/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/influxdb-0.8.1/lib/influxdb/client/http.rb:11:in `get'
        2: from /home/bs/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/influxdb-0.8.1/lib/influxdb/client/http.rb:53:in `connect_with_retry'
        1: from /home/bs/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/influxdb-0.8.1/lib/influxdb/client/http.rb:19:in `block in get'
/home/bs/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/influxdb-0.8.1/lib/influxdb/client/http.rb:86:in `resolve_error': {"error":"error parsing query: found /, expected ; at line 1, char 22"} (InfluxDB::Error)
```
I tried escaping the "/" with a backslash which also gives me an error: `found \\\\, expected regex at line 1, char 22`

How can i query for a measurement containing a slash?

**Comment by BernH4** [comment]
Got it, Influx thinks its a regex. Just quoting the whole measurement solves it:
```rb
influxdb.query('select * from "heizung/pufferspeicher/temp"')
```
